version: 0.2

env:
  variable:
    $MAVEN_VERSION: 3.5.4

phases:
  install:
    runtime-versions:
      java: corretto8
       
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase..
      - mvn -v
    finally:
      - echo Nothing to do in the finally...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/APP.jar
  name: Cox-dev-Buildnumber-$CODEBUILD_BUILD_NUMBER-$(date +%Y-%m-%d)